//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report_Fas_SMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAS_ShiftPlan
    {
        public byte ID { get; set; }
        public byte LineID { get; set; }
        public short ShiftPlan { get; set; }
        public Nullable<short> ModelID { get; set; }
    
        public virtual FAS_Models FAS_Models { get; set; }
    }
}
