//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report_Fas_SMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAS_Disassembly
    {
        public int ID { get; set; }
        public Nullable<int> SerialNumber { get; set; }
        public string FullSTBSN { get; set; }
        public int PCBID { get; set; }
        public short LOTID { get; set; }
        public short ErrorCodeID { get; set; }
        public byte DisAssemblyLineID { get; set; }
        public System.DateTime DisassemblyDate { get; set; }
        public Nullable<short> DisassemblyByID { get; set; }
    }
}
