//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report_Fas_SMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAS_Models
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAS_Models()
        {
            this.FAS_GS_LOTs = new HashSet<FAS_GS_LOTs>();
            this.FAS_ShiftPlan = new HashSet<FAS_ShiftPlan>();
        }
    
        public short ModelID { get; set; }
        public string ModelName { get; set; }
        public byte ModelTypeID { get; set; }
        public string DelaySetting { get; set; }
        public string TopMask { get; set; }
        public string BotMask { get; set; }
        public Nullable<short> lenHDCP { get; set; }
        public Nullable<short> ChipCode { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> IDQuality { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAS_GS_LOTs> FAS_GS_LOTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAS_ShiftPlan> FAS_ShiftPlan { get; set; }
    }
}
