//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report_Fas_SMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAS_Objective
    {
        public int ID { get; set; }
        public string NameProduct { get; set; }
        public string Mask { get; set; }
        public Nullable<decimal> Cell { get; set; }
        public string Prod { get; set; }
    }
}
