//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report_Fas_SMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAS_PackingCounter
    {
        public int ID { get; set; }
        public short PalletCounter { get; set; }
        public short BoxCounter { get; set; }
        public short UnitCounter { get; set; }
        public byte LineID { get; set; }
        public short LOTID { get; set; }
        public Nullable<short> LitIndex { get; set; }
    }
}
