//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report_Fas_SMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class KGP_Control_Sputnik
    {
        public int ID { get; set; }
        public Nullable<short> Pass { get; set; }
        public Nullable<short> Fail { get; set; }
        public string DefectCode { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<short> TestByStart { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<short> TestByEnd { get; set; }
        public string Description { get; set; }
        public string ControlMode { get; set; }
    }
}
